import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-tw">
      <body>
        <Navbar />
        <Hero />
        {children}
      </body>
    </html>
  );
}
